#!/usr/bin/env python3
"""Voice Studio PRODUCTION adapter (2026-10-06) - the live clone-voice manager.

Sits in front of the 1.7B-Base clone engine (qwen3-tts-base.service, :7869,
CPU) and manages the shared voice library (/opt/qwen3-tts/voice_library):

  GET  /health                     -> adapter + upstream status
  GET  /v1/voices                  -> proxied from upstream (lists clone:<name>)
  POST /v1/voice/clone             -> one-shot clone+synth ("Test voice")
  POST /v1/voice/profiles          -> SAVE a named voice profile ("Name it")
  GET  /v1/voice/profiles          -> list saved profiles
  DELETE /v1/voice/profiles/<name> -> remove a profile
  GET  /studio                     -> the Voice Studio page (HTML)

Every save/delete also regenerates the portal's static voice-list file
(env VOX_VOICES_FILE, default /opt/pithagoras/web/avatar/kokoro-voices.js -
a host-side copy bind-mounted over the in-image path) so the avatar page's
picker lists new "Cloned" voices immediately, no rebuild.

LAN-reachable (BIND=0.0.0.0); the TTS engine stays loopback-only.
Pure stdlib; runs as a plain systemd service (no Docker).
"""
import base64
import io
import json
import os
import re
import socket
import time
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

UPSTREAM = os.environ.get("VOX_UPSTREAM", "http://127.0.0.1:7869").rstrip("/")
PORT = int(os.environ.get("PORT", "7871"))
BIND = os.environ.get("BIND", "0.0.0.0")
# Keep the profile library identical to what production will use, minus the
# live data: a dedicated test dir so nothing leaks into prod.
VOICE_LIBRARY_DIR = os.environ.get(
    "VOICE_LIBRARY_DIR", "/opt/qwen3-tts/voice_library"
)
NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _\-']{0,31}$")
MAX_REF_BYTES = 12 * 1024 * 1024  # 12 MB (30s of 24-bit audio is ~2MB; be generous)
# The portal avatar page's static voice list: in-image at
# /app/web/dist/avatar/kokoro-voices.js, mirrored on the host and bind-mounted
# over that path. After every profile save/delete we rewrite it with the 9
# presets + a "Cloned" group so the picker stays in sync. Best-effort; never
# fatal to the request path.
VOICES_FILE = os.environ.get("VOX_VOICES_FILE", "/opt/pithagoras/web/avatar/kokoro-voices.js")

def regenerate_voices_file(clones):
    """Rewrite VOICES_FILE with the 9 preset speakers + one 'Cloned' group."""
    if not VOICES_FILE:
        return False
    try:
        presets = [
            ("vivian",   "F", "Vivian · young female · bright, slightly edgy (default)"),
            ("serena",   "F", "Serena · young female · warm, gentle"),
            ("ono_anna", "F", "Ono Anna · Japanese female · playful, light, nimble"),
            ("sohee",    "F", "Sohee · Korean female · warm, rich emotion"),
            ("ryan",     "M", "Ryan · male · dynamic, strong rhythmic drive"),
            ("aiden",    "M", "Aiden · American male · sunny, clear midrange"),
            ("dylan",    "M", "Dylan · Beijing male · clear, natural"),
            ("eric",     "M", "Eric · Chengdu male · lively, slightly husky"),
            ("uncle_fu", "M", "Uncle Fu · seasoned male · low, mellow timbre"),
        ]
        lines = [
            "// TTS engine voices available on the local TTS backend.",
            "// AUTO-GENERATED by the Voice Studio adapter (:7871) - do not edit.",
            "// 9 preset speakers (Qwen3-TTS 1.7B-CustomVoice, GPU) plus cloned",
            "// voices (1.7B-Base voice library, CPU clone engine :7869).",
            'window.KOKORO_DEFAULT_VOICE = "vivian";',
            "window.KOKORO_VOICES = [",
        ]
        for vid, grp, label in presets:
            lines.append('  { id: "%s", g: "%s", t: "%s" },' % (vid, grp, label))
        for c in sorted(clones):
            name = (c or "").split(":", 1)[1].strip()
            lines.append('  { id: "clone:%s", g: "C", t: "%s · cloned voice" },' % (name, name))
        lines.append("];")
        lines.append("window.KOKORO_LABELS = Object.fromEntries(window.KOKORO_VOICES.map(v => [v.id, v.t]));")
        content = "\n".join(lines) + "\n"
        tmp = VOICES_FILE + ".tmp"
        with open(tmp, "w") as f:
            f.write(content)
        os.replace(tmp, VOICES_FILE)
        print(f"  -> voices file regenerated ({len(clones)} clone(s)) -> {VOICES_FILE}", flush=True)
        _push_voices_into_container(content)
        return True
    except Exception as e:
        print(f"  -> voices-file regen FAILED (non-fatal): {e!r}", flush=True)
        return False

def _push_voices_into_container(content):
    """Mirror the file into the LIVE pithagoras portal container
    (/app/web/dist/avatar/kokoro-voices.js is image-layer, not bind-mounted,
    so a direct docker-exec write is the least-invasive way to update the
    avatar picker without recreating the production container).
    Best-effort; a failure here never breaks the save."""
    try:
        import subprocess
        r = subprocess.run(
            ["docker", "exec", "-i", "pithagoras", "sh", "-c",
             "cat > /app/web/dist/avatar/kokoro-voices.js"],
            input=content.encode(), timeout=30)
        if r.returncode == 0:
            print("  -> portal container voice list updated (in-container copy)", flush=True)
        else:
            print(f"  -> in-container push rc={r.returncode} (non-fatal)", flush=True)
    except Exception as e:
        print(f"  -> in-container push FAILED (non-fatal): {e!r}", flush=True)


def _upstream_json(method, path, payload=None, timeout=240):
    """Call the upstream FastAPI server (urllib is fine here - this is the
    Qwen3-TTS server, not Kokoro's 401-quirky parser)."""
    url = UPSTREAM + path
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, r.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()


def _save_profile(name, ref_audio_b64, ref_text, x_vector_only, language):
    profiles = os.path.join(VOICE_LIBRARY_DIR, "profiles")
    os.makedirs(profiles, exist_ok=True)
    # one canonical dir per (case-insensitive) name
    target = None
    for child in os.listdir(profiles):
        d = os.path.join(profiles, child)
        meta_p = os.path.join(d, "meta.json")
        if os.path.isdir(d) and os.path.exists(meta_p):
            try:
                m = json.load(open(meta_p))
                if str(m.get("name", "")).lower() == name.lower():
                    target = d
                    break
            except Exception:
                continue
    if target is None:
        target = os.path.join(profiles, name + "_" + time.strftime("%Y%m%d"))
        os.makedirs(target, exist_ok=True)
    ref_bytes = base64.b64decode(ref_audio_b64)
    if not ref_bytes:
        raise ValueError("empty reference audio")
    ref_filename = "ref_audio" + os.path.splitext(
        os.path.basename(name.replace(" ", "_"))
    )[1].lower() if "." in name else ".wav"
    if not ref_filename.startswith("."):
        ref_filename = ".wav" + ref_filename[1:]
    ref_path = os.path.join(target, "ref_audio.wav")
    with open(ref_path, "wb") as f:
        f.write(ref_bytes)
    meta = {
        "profile_id": f"clone:{name}",
        "name": name,
        "ref_audio_filename": "ref_audio.wav",
        "ref_text": ref_text or "",
        "x_vector_only_mode": bool(x_vector_only),
        "language": language or "Auto",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": "voice-studio",
    }
    with open(os.path.join(target, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return target


def _list_profiles():
    profiles = os.path.join(VOICE_LIBRARY_DIR, "profiles")
    out = []
    if not os.path.isdir(profiles):
        return out
    for child in sorted(os.listdir(profiles)):
        d = os.path.join(profiles, child)
        meta_p = os.path.join(d, "meta.json")
        if not (os.path.isdir(d) and os.path.exists(meta_p)):
            continue
        try:
            m = json.load(open(meta_p))
            out.append({
                "id": f"clone:{m.get('name', child)}",
                "name": m.get("name", child),
                "ref_text": m.get("ref_text", ""),
                "x_vector_only_mode": m.get("x_vector_only_mode", False),
                "language": m.get("language", "Auto"),
                "has_audio": os.path.exists(
                    os.path.join(d, m.get("ref_audio_filename", ""))
                ),
            })
        except Exception:
            continue
    return out


STUDIO_HTML = r"""<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Voice Studio (test)</title>
<style>
body{font-family:system-ui,sans-serif;max-width:820px;margin:32px auto;padding:0 16px;color:#222;background:#fafafa}
h1{font-size:22px}h2{font-size:16px;margin:28px 0 8px}
.card{background:#fff;border:1px solid #ddd;border-radius:10px;padding:16px 20px;margin:12px 0}
label{display:block;margin:10px 0 4px;font-size:13px;color:#444}
input[type=text],textarea{width:100%;box-sizing:border-box;padding:8px;border:1px solid #ccc;border-radius:6px;font-size:14px}
button{background:#2563eb;color:#fff;border:0;border-radius:6px;padding:9px 18px;font-size:14px;cursor:pointer;margin:10px 6px 0 0}
button:disabled{opacity:.5;cursor:wait}
.rec{background:#dc2626}.rec.on{animation:pulse 1s infinite}
@keyframes pulse{50%{opacity:.6}}
audio{width:100%;margin-top:8px}
.ok{color:#166534}.err{color:#b91c1c}.muted{color:#888;font-size:12px}
#voices li{margin:4px 0}
small{color:#666}
</style></head><body>
<h1>Voice Studio <small>(live - voices appear in the avatar menu under Cloned)</small></h1>

<div class="card">
<h2>1. Reference sample (3-30 s, one person, quiet room)</h2>
<input type="file" id="file" accept="audio/*" onchange="onFile(this)">
<button id="recBtn" class="rec" onclick="toggleRec()">&#9679; Record from mic</button>
<span id="recInfo" class="muted"></span>
<div id="refPrev"></div>
<label>Transcript of the sample <small>(optional - best quality; leave blank for x-vector mode which needs no typing)</small></label>
<textarea id="refText" rows="2" placeholder="Type exactly what is said in the sample, if you know it..."></textarea>
</div>

<div class="card">
<h2>2. Test it</h2>
<label>Test sentence</label>
<input type="text" id="testText" value="Hello! This is a test of the voice cloning feature on Pithagoras.">
<button id="testBtn" onclick="testVoice()">Generate test</button>
<div id="testPrev"></div>
</div>

<div class="card">
<h2>3. Make it official</h2>
<label>Voice name <small>(appears in the avatar menu as: clone:&lt;name&gt;)</small></label>
<input type="text" id="name" placeholder="e.g. Sean" maxlength="32" oninput="document.getElementById('namePrev').textContent='clone:'+(this.value||'...')">
<span id="namePrev" class="muted">clone:...</span>
<button id="saveBtn" onclick="saveVoice()">Save voice</button>
<span id="saveInfo" class="muted"></span>
</div>

<div class="card">
<h2>Your voices <button style="background:#888" onclick="loadVoices()">&#8635; refresh</button></h2>
<ul id="voices"></ul>
</div>

<script>
let refB64=null, refMime='audio/wav', rec=null, chunks=[];
// Convert any browser audio (uploaded file or mic webm/opus) to 16-bit 16 kHz
// mono WAV via WebAudio - the TTS server's soundfile decoder only accepts
// WAV/FLAC/OGG/MP3, never WebM/Opus.
async function toWavB64(blob){
  const arr=await blob.arrayBuffer();
  const AC=window.AudioContext||window.webkitAudioContext;
  const ac=new AC();
  let audio;
  try{ audio=await ac.decodeAudioData(arr.slice(0)); }
  catch(e){ ac.close(); throw new Error('Could not decode that audio format: '+e.message); }
  ac.close();
  const target=16000;
  const off=new OfflineAudioContext(1, Math.max(1,Math.ceil(audio.duration*target)), target);
  const src=off.createBufferSource(); src.buffer=audio; src.connect(off.destination); src.start(0);
  const rendered=await off.startRendering();
  const ch=rendered.getChannelData(0);
  const pcm=new Int16Array(ch.length);
  for(let i=0;i<ch.length;i++){ let v=Math.max(-1,Math.min(1,ch[i])); pcm[i]=v<0?Math.round(v*32768):Math.round(v*32767); }
  const head=new ArrayBuffer(44);
  const dv=new DataView(head);
  const ws=(o,s)=>{for(let i=0;i<s.length;i++)dv.setUint8(o+i,s.charCodeAt(i));};
  ws(0,'RIFF'); dv.setUint32(4,36+pcm.length*2,true); ws(8,'WAVE'); ws(12,'fmt ');
  dv.setUint32(16,16,true); dv.setUint16(20,1,true); dv.setUint16(22,1,true);
  dv.setUint32(24,target,true); dv.setUint32(28,target*2,true); dv.setUint16(32,2,true);
  dv.setUint16(34,16,true); ws(36,'data'); dv.setUint32(40,pcm.length*2,true);
  const buf=new ArrayBuffer(44+pcm.length*2);
  new Uint8Array(buf).set(new Uint8Array(head),0);
  new Int16Array(buf,44).set(pcm);
  let s=''; const u=new Uint8Array(buf);
  for(let i=0;i<u.length;i+=0x8000) s+=String.fromCharCode.apply(null,u.subarray(i,i+0x8000));
  return btoa(s);
}
function showRef(msg){ if(!refB64)return; document.getElementById('refPrev').innerHTML='<audio controls src="data:'+refMime+';base64,'+refB64+'"></audio> <small>'+msg+'</small>'; }
async function onFile(el){ if(!el.files[0])return;
  const f=el.files[0];
  const b64=await toWavB64(f);
  refB64=b64; refMime='audio/wav';
  showRef('converted to 16-bit WAV, '+(b64.length*3/4/1024|0)+' KB ('+(f.size/1024|0)+' KB original)');
}
async function toggleRec(){
  const btn=document.getElementById('recBtn'), info=document.getElementById('recInfo');
  if(rec){ rec.stop(); return; }
  const mime=[ 'audio/webm','audio/ogg;codecs=opus','audio/mp4' ].find(m=>MediaRecorder.isTypeSupported(m)) || '';
  const s=await navigator.mediaDevices.getUserMedia({audio:true});
  rec=new MediaRecorder(s, mime?{mimeType:mime}:{}); chunks=[];
  rec.ondataavailable=e=>chunks.push(e.data);
  rec.onstop=async()=>{ s.getTracks().forEach(t=>t.stop());
    const b=new Blob(chunks,{type:rec.mimeType||'audio/webm'});
    try{ refB64=await toWavB64(b); refMime='audio/wav'; showRef('recorded '+(b.size/1024|0)+' KB -> 16-bit WAV'); }
    catch(err){ info.innerHTML='<span class="err">'+err.message+'</span>'; }
    btn.classList.remove('on'); btn.innerHTML='&#9679; Record from mic'; info.textContent='';
  };
  rec.start(); btn.classList.add('on'); btn.innerHTML='&#9633; Stop recording'; info.textContent='recording...';
}
async function postJson(url, body){ const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  const t=await r.text(); let j; try{ j=JSON.parse(t);}catch(e){ j={error:t.slice(0,300)}; } return {ok:r.ok, status:r.status, data:j}; }
function audioB64(b64, type){ const u=new URL('data:'+type+';base64,'+b64); const d=document.createElement('div'); d.innerHTML='<audio controls src="'+u+'" style="width:100%"></audio>'; return d.innerHTML; }
async function testVoice(){
  if(!refB64){ alert('Provide a reference sample first (file or mic).'); return; }
  const btn=document.getElementById('testBtn'), prev=document.getElementById('testPrev');
  btn.disabled=true; btn.textContent='Synthesizing (CPU - can take a minute)...';
  prev.innerHTML='<small>working on it - first run loads the model...</small>';
  const r=await postJson('/v1/voice/clone', {ref_audio:refB64, text:document.getElementById('testText').value,
    ref_text:document.getElementById('refText').value.trim(),
    x_vector_only_mode:!document.getElementById('refText').value.trim(),
    response_format:'wav'});
  btn.disabled=false; btn.textContent='Generate test';
  if(r.ok && r.data.audio_b64){ prev.innerHTML=audioB64(r.data.audio_b64,'audio/wav')+' <small class="ok">'+(r.data.seconds?r.data.seconds+'s @ '+(r.data.sr||24000)+'Hz':'ok')+'</small>'; }
  else { prev.innerHTML='<span class="err">FAIL ('+r.status+'): '+JSON.stringify(r.data).slice(0,400)+'</span>'; }
}
async function saveVoice(){
  if(!refB64){ alert('Provide a reference sample first.'); return; }
  const name=document.getElementById('name').value.trim();
  if(!/^[A-Za-z0-9][A-Za-z0-9 _\-']{0,31}$/.test(name)){ alert('Name: start with a letter/digit, then letters/digits/space/hyphen (max 32).'); return; }
  const btn=document.getElementById('saveBtn'), info=document.getElementById('saveInfo');
  btn.disabled=true; info.textContent='saving...';
  const r=await postJson('/v1/voice/profiles', {name:name, ref_audio:refB64,
    ref_text:document.getElementById('refText').value.trim(),
    x_vector_only_mode:!document.getElementById('refText').value.trim(),
    language:'auto'});
  btn.disabled=false;
  if(r.ok){ info.innerHTML='<span class="ok">Saved clone:'+name+'</span>'; loadVoices(); }
  else { info.innerHTML='<span class="err">FAIL: '+JSON.stringify(r.data).slice(0,300)+'</span>'; }
}
async function loadVoices(){
  const r=await fetch('/v1/voices'); const d=await r.json();
  const ul=document.getElementById('voices'); ul.innerHTML='';
  (d.voices||[]).forEach(v=>{
    const li=document.createElement('li');
    if(v.id&&v.id.startsWith('clone:')){
      li.innerHTML='<b>'+v.id+'</b> <span class="muted">'+(v.description||'')+'</span> '
        +'<button onclick="testNamed(this,\''+v.id+'\')">&#9654; test</button> '
        +'<button onclick="delProfile(\''+v.id+'\')" style="background:#b91c1c">&#10005; delete</button>';
      li._t=document.createElement('div'); li.appendChild(li._t);
      ul.appendChild(li);
    } else {
      li.innerHTML='<span class="muted">'+v.id+'</span> <span class="muted">(preset - not cloneable on the Base model)</span>';
      ul.appendChild(li);
    }
  });
  if(!ul.children.length) ul.innerHTML='<li class="muted">no voices yet</li>';
}
async function testNamed(btn, id){
  const r=await postJson('/v1/voice/clone', {profile:id, text:document.getElementById('testText').value, response_format:'wav'});
  const holder=btn.closest('li')._t||btn.parentElement;
  if(r.ok && r.data.audio_b64){ holder.innerHTML=audioB64(r.data.audio_b64,'audio/wav'); }
  else { holder.innerHTML='<span class="err">FAIL: '+JSON.stringify(r.data).slice(0,300)+'</span>'; }
}
async function delProfile(id){
  if(!confirm('Delete '+id+'?')) return;
  const r=await fetch('/v1/voice/profiles/'+encodeURIComponent(id.replace(/^clone:/,'')),{method:'DELETE'});
  if(r.ok) loadVoices(); else alert('delete failed: '+r.status);
}
loadVoices();
</script></body></html>
"""


class H(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def _send(self, code, body=b"", ctype="application/json"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Connection", "close")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)
        self.close_connection = True

    def _body(self, max_bytes=32 * 1024 * 1024):
        cl = int(self.headers.get("Content-Length") or 0)
        if cl > max_bytes:
            raise ValueError("request too large")
        return self.rfile.read(cl) if cl else b""

    def do_GET(self):
        path = self.path.split("?")[0]
        if path in ("/health", ""):
            status_code, body = _upstream_json("GET", "/v1/audio/voice-clone/capabilities")
            cap = {}
            try:
                cap = json.loads(body)
            except Exception:
                pass
            self._send(200, json.dumps({
                "status": "ok", "role": "voice-studio-adapter",
                "upstream": UPSTREAM, "capabilities": cap,
                "voice_library": VOICE_LIBRARY_DIR,
                "profiles": len(_list_profiles()),
            }).encode())
        elif path == "/v1/voices":
            code, body = _upstream_json("GET", "/v1/audio/voices")
            # augment with local profile detail (description + delete info)
            try:
                d = json.loads(body)
                mine = {p["id"]: p for p in _list_profiles()}
                for v in d.get("voices", []):
                    if v.get("id") in mine:
                        p = mine[v["id"]]
                        v["description"] = (
                            "Cloned voice%s" % (" (x-vector)" if p["x_vector_only_mode"] else " (ICL)")
                            + (" | language:" + p["language"] if p.get("language") else "")
                        )
                self._send(200, json.dumps(d).encode())
            except Exception:
                self._send(code, body)
        elif path == "/v1/voice/profiles":
            self._send(200, json.dumps({"profiles": _list_profiles()}).encode())
        elif path == "/studio":
            self._send(200, STUDIO_HTML.encode(), "text/html; charset=utf-8")
        else:
            self._send(404, b'{"error":"not found"}')

    def do_POST(self):
        path = self.path.split("?")[0]
        t0 = time.time()
        try:
            body = json.loads(self._body())
            if path == "/v1/voice/clone":
                ref_b64 = body.get("ref_audio") or ""
                text = body.get("text") or ""
                if body.get("profile"):
                    # test an already-saved profile
                    pdir = os.path.join(
                        VOICE_LIBRARY_DIR, "profiles")
                    name = body["profile"][6:] if body["profile"].startswith("clone:") else body["profile"]
                    found = False
                    for child in os.listdir(pdir):
                        mp = os.path.join(pdir, child, "meta.json")
                        if os.path.exists(mp):
                            m = json.load(open(mp))
                            if m.get("name", "").lower() == name.lower():
                                ref_b64 = base64.b64encode(
                                    open(os.path.join(pdir, child, m["ref_audio_filename"]), "rb").read()).decode()
                                text = text or "Testing the saved voice."
                                body.setdefault("ref_text", m.get("ref_text", ""))
                                body.setdefault("x_vector_only_mode", m.get("x_vector_only_mode", False))
                                found = True
                                break
                    if not found:
                        self._send(404, json.dumps({"error": "profile not found: " + name}).encode())
                        return
                if not text:
                    text = "Testing the cloned voice."
                payload = {
                    "input": text,
                    "ref_audio": ref_b64,
                    "ref_text": body.get("ref_text") or "",
                    "x_vector_only_mode": bool(body.get("x_vector_only_mode", True)),
                    "language": body.get("language") or "Auto",
                    "response_format": body.get("response_format") or "wav",
                }
                if not payload["x_vector_only_mode"] and not payload["ref_text"]:
                    self._send(400, json.dumps({"error": "ICL mode requires ref_text, or set x_vector_only_mode=true"}).encode())
                    return
                code, raw = _upstream_json("POST", "/v1/audio/voice-clone", payload)
                if code != 200:
                    self._send(code, raw)
                    return
                # upstream returns the encoded audio BINARY (wav/mp3/...) - re-emit
                # as JSON base64 so the browser <audio> tag can play it
                b64 = base64.b64encode(raw).decode()
                fmt = payload["response_format"]
                self._send(200, json.dumps({
                    "audio_b64": b64,
                    "format": fmt,
                    "bytes": len(raw),
                    "elapsed": round(time.time() - t0, 1),
                }).encode())
            elif path == "/v1/voice/profiles":
                name = (body.get("name") or "").strip()
                if not NAME_RE.fullmatch(name):
                    self._send(400, json.dumps({"error": "invalid name"}).encode())
                    return
                ref_b64 = body.get("ref_audio") or ""
                if not ref_b64:
                    self._send(400, json.dumps({"error": "ref_audio (base64) required"}).encode())
                    return
                ref_bytes = base64.b64decode(ref_b64)
                if len(ref_bytes) > MAX_REF_BYTES:
                    self._send(413, json.dumps({"error": "sample too large"}).encode())
                    return
                pdir = _save_profile(name, ref_b64, body.get("ref_text") or "",
                                     body.get("x_vector_only_mode", True),
                                     body.get("language") or "Auto")
                clones = [pp["id"] for pp in _list_profiles()]
                regenerate_voices_file(clones)
                self._send(201, json.dumps({"ok": True, "id": "clone:" + name, "path": pdir}).encode())
            else:
                self._send(404, b'{"error":"not found"}')
        except Exception as e:
            self._send(500, json.dumps({"error": repr(e)}).encode())

    def do_DELETE(self):
        path = self.path.split("?")[0]
        if path.startswith("/v1/voice/profiles/"):
            import urllib.parse
            name = urllib.parse.unquote(path[len("/v1/voice/profiles/"):])
            pdir = os.path.join(VOICE_LIBRARY_DIR, "profiles")
            done = False
            for child in os.listdir(pdir) if os.path.isdir(pdir) else []:
                d = os.path.join(pdir, child)
                mp = os.path.join(d, "meta.json")
                if os.path.isdir(d) and os.path.exists(mp):
                    m = json.load(open(mp))
                    if m.get("name", "").lower() == name.lower():
                        import shutil
                        shutil.rmtree(d)
                        done = True
                        break
            if done:
                clones = [pp["id"] for pp in _list_profiles()]
                regenerate_voices_file(clones)
            self._send(200 if done else 404, json.dumps({"deleted": done}).encode())
        else:
            self._send(404, b'{"error":"not found"}')

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    print(f"voice-studio adapter on {BIND}:{PORT} -> {UPSTREAM} (lib={VOICE_LIBRARY_DIR}, voices={VOICES_FILE})", flush=True)
    # Bring the avatar picker in line with any profiles already in the library.
    try:
        regenerate_voices_file([p["id"] for p in _list_profiles()])
    except Exception as e:
        print(f"startup voices regen FAILED (non-fatal): {e!r}", flush=True)
    ThreadingHTTPServer((BIND, PORT), H).serve_forever()
